FourthCircle/Models/EntityViewModels/LogbookViewModel.cs
using FourthCircle.Data.Entities;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FourthCircle.Models.EntityViewModels
{
    public class LogbookViewModel
    {
        public LogbookViewModel()
        {
            Categories = new List<string>();
            AssignedManagers = new List<string>();
            Notes = new List<Note>();
            Comments = new List<Comment>();
        }

        public string Id { get; set; }
        [Required]
        public string Name { get; set; }
        [Required]
        public string LocationName { get; set; }
        public ICollection<string> Categories { get; set; }
        public ICollection<string> AssignedManagers { get; set; }
        public ICollection<Note> Notes { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }
}

FourthCircle/Models/EntityViewModels/NoteViewModel.cs
using FourthCircle.Data.Entities;
using Microsoft.AspNetCore.Http;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FourthCircle.Models.EntityViewModels
{
    public class NoteViewModel
    {
        public NoteViewModel()
        {
            Categories = new List<string>();
        }

        public string Id { get; set; }
        [Required]
        [StringLength(280, MinimumLength = 5, ErrorMessage = "Please enter text between 5 and 280 characters.")]
        public string Text { get; set; }
        public ICollection<string> Categories { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public byte[] UserAvatar { get; set; }
        public bool IsMarkedAsSolved { get; set; }
        public ApplicationUser SolvedByUser { get; set; }
        public bool AddAsComment { get; set; }
        public byte[] Picture { get; set; }
        public IFormFile UploadFormPicture { get; set; }
        public string LogbookID { get; set; }
        public Logbook Logbook { get; set; }
        public string CreatedOn { get; set; }
    }
}

FourthCircle/Areas/Management/Controllers/LogbooksController.cs
using Exceptionless;
using FourthCircle.Data.Entities;
using FourthCircle.Mappers;
using FourthCircle.Models.EntityViewModels;
using FourthCircle.Services.Interfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.IO;
using System.Linq;
using X.PagedList;

namespace FourthCircle.Areas.Management.Controllers
{
    [Area("Management")]
    [Authorize(Roles = "Manager")]
    public class LogbooksController : Controller
    {
        private readonly ILogbookService logbookService;
        private readonly ILocationService locationService;
        private readonly IManagerService managerService;
        private readonly LogbookViewModelMapper logbookMapper;
        private readonly LocationViewModelMapper locationMapper;
        private readonly NoteViewModelMapper noteMapper;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly ICommentService commentService;
        private readonly IUserService userService;

        public LogbooksController(ILogbookService logbookService, LogbookViewModelMapper logbookMapper, NoteViewModelMapper noteMapper, IManagerService managerService,
            UserManager<ApplicationUser> userManager, ILocationService locationService, LocationViewModelMapper locationMapper, ICommentService commentService, IUserService userService)
        {
            this.locationService = locationService;
            this.logbookService = logbookService;
            this.logbookMapper = logbookMapper;
            this.locationMapper = locationMapper;
            this.managerService = managerService;
            this.userManager = userManager;
            this.noteMapper = noteMapper;
            this.commentService = commentService;
            this.userService = userService;
        }

        public IActionResult Index()
        {
            var userId = userManager.GetUserId(User);
            if (userId == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            var vm = locationService.GetLocationsByUser(userId).Select(locationMapper.MapFrom);

            return View(vm);
        }

        public IActionResult Notes(string Id, int? page, string searchString, string category, DateTime? dateFrom, DateTime? dateTo, bool showAll)
        {
            IPagedList<NoteViewModel> vm;
            try
            {
                if (showAll == true)
                {
                    vm = managerService.FilterLogbookNotes(Id, category, searchString, dateFrom, dateTo)
                    .Select(noteMapper.MapFrom)
                    .ToPagedList(page ?? 1, 7);
                }
                else
                {
                    vm = managerService.FilterLogbookNotes(Id, category, searchString, dateFrom, dateTo).Where(x => x.IsMarkedAsSolved == false)
                    .Select(noteMapper.MapFrom)
                    .ToPagedList(page ?? 1, 7);
                }
            }
            catch (Exception)
            {
                ExceptionlessClient.Default.SubmitNotFound($"/Management/Logbooks/Notes/{Id}");
                return BadRequest();
            }

            ViewBag.logbookId = Id;
            ViewBag.categories = GetCategoryViewBagByLogbook(Id);
            ViewBag.category = category;
            ViewBag.searchString = searchString;
            ViewBag.dateFrom = dateFrom;
            ViewBag.dateTo = dateTo;
            ViewBag.showAll = showAll;
            return View(vm);
        }

        public IActionResult MarkNoteAsSolved(string id, string logbookId, int? page, string searchString, string category, DateTime? dateFrom, DateTime? dateTo, bool showAll)
        {
            var userId = userManager.GetUserId(User);

            try
            {
                managerService.MarkNoteAsSolved(userId, id, logbookId);
            }
            catch (Exception)
            {
                ExceptionlessClient.Default.SubmitNotFound($"/Management/Logbooks/MarkNoteAsSolved?logbookId={logbookId}&noteId={id}");
                return BadRequest();
            }

            IPagedList<NoteViewModel> vm;
            if (showAll == true)
            {
                vm = managerService.FilterLogbookNotes(logbookId, category, searchString, dateFrom, dateTo)
                .Select(noteMapper.MapFrom)
                .ToPagedList(page ?? 1, 7);
            }
            else
            {
                vm = managerService.FilterLogbookNotes(logbookId, category, searchString, dateFrom, dateTo).Where(x => x.IsMarkedAsSolved == false)
                .Select(noteMapper.MapFrom)
                .ToPagedList(page ?? 1, 7);
            }

            ViewBag.logbookId = logbookId;
            ViewBag.categories = GetCategoryViewBagByLogbook(logbookId);
            ViewBag.category = category;
            ViewBag.searchString = searchString;
            ViewBag.dateFrom = dateFrom;
            ViewBag.dateTo = dateTo;
            ViewBag.showAll = showAll;
            return View("Notes", vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async System.Threading.Tasks.Task<IActionResult> AddNoteAsync(NoteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View("AddNote", model);
            }

            try
            {
                var userId = userManager.GetUserId(User);
                if (userId == null)
                {
                    throw new ApplicationException($"Unable to load user with ID '{userId}'.");
                }

                managerService.AddNote(
                        userId, model.Text, model.LogbookID, model.Categories, model.UploadFormPicture);
                var state = ModelState.IsValid;
                return RedirectToAction("Notes", new { Id = model.LogbookID });
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View("AddNote", new NoteViewModel { Id = model.LogbookID });
            }
        }

        [HttpGet]
        public IActionResult EditNote(string logbookId, string noteId)
        {
            var userId = userManager.GetUserId(User);
            if (userId == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            ViewBag.categories = GetCategoryViewBagByLogbook(logbookId);

            var vm = noteMapper.MapFrom(managerService.GetNoteById(noteId), userId, logbookId);

            return View(vm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult EditNote(NoteViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            try
            {
                managerService.EditNote(
                    model.UserID, model.Id, model.LogbookID, model.Text, model.Categories);
                return RedirectToAction("Notes", new { Id = model.LogbookID });
            }
            catch (ArgumentException ex)
            {
                ModelState.AddModelError("Error", ex.Message);
                return View(new NoteViewModel { Id = model.LogbookID });
            }
        }

        public IActionResult DeleteNote(string logbookId, string noteId)
        {
            var userId = userManager.GetUserId(User);
            if (userId == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            ViewBag.categories = GetCategoryViewBagByLogbook(logbookId);

            try
            {
                managerService.DeleteNote(userId, noteId, logbookId);
                return RedirectToAction("Notes", new { Id = logbookId });
            }
            catch (Exception)
            {
                ExceptionlessClient.Default.SubmitNotFound($"/Management/Logbooks/DeleteNote/?logbookId={logbookId}&noteId={noteId}");
                return BadRequest();
            }
        }

        [HttpGet]
        public IActionResult AddCommentAsNote(string commentId)
        {
            var userId = userManager.GetUserId(User);
            if (userId == null)
            {
                throw new ApplicationException($"Unable to load user with ID '{userId}'.");
            }

            ViewBag.logbooks = logbookService.GetLogbooksByUser(userId).Select(logbookMapper.MapFrom);

            var comment = commentService.GetCommentById(commentId);

            var model = new NoteViewModel
            {
                UserID = userId,
                Text = comment.Text.Insert(0, $"Customer comment from \"{comment.Author}\":\n")
            };

            return PartialView("AddCommentAsNote", model);
        }

        public JsonResult CategoryDropDownList(string logbookId)
        {
            var categories = managerService.GetLogbookCategories(logbookId);

            //db.PageStats.Where(x => x.Country.Equals(country)).OrderBy(x => x.City).Select(x => x.City).Distinct().ToList();

            //ViewBag.categories = GetCategoryViewBagByLogbook(Id);

            //List<SelectListItem> cities = new List<SelectListItem>();

            //foreach (var item in results)
            //{
            //    SelectListItem city = new SelectListItem
            //    {
            //        Text = item,
            //        Value = item
            //    };
            //    cities.Add(city);
            //}
            return Json(categories);
        }

        [HttpPost]
        //[ValidateAntiForgeryToken]
        //[Consumes("multipart/form-data")]
        public async System.Threading.Tasks.Task<IActionResult> AddCommentAsNote(NoteViewModel model)
        {
            if (!ModelState.IsValid)
            {

FourthCircle/Controllers/ImagesController.cs
using FourthCircle.Services.Interfaces;
using Microsoft.AspNetCore.Mvc;

namespace FourthCircle.Controllers
{
    public class ImagesController : Controller
    {
        readonly IUserService userService;
        readonly IManagerService managerService;

        public ImagesController(IUserService userService, IManagerService managerService)
        {
            this.userService = userService;
            this.managerService = managerService;
        }

        public IActionResult GetUserAvatar(string userId)
        {
            byte[] image = userService.GetUserAvatar(userId);
            return File(image, "image/png");
        }

        public IActionResult GetUploadImage(string noteId)
        {
            byte[] image = managerService.GetNoteById(noteId).Picture;
            return File(image, "image/JPEG");
        }
    }
}

FourthCircle/Areas/Management/Views/Logbooks/AddCommentAsNote.cshtml
@using FourthCircle.Models.EntityViewModels;
@model NoteViewModel

<div class="modal fade" id="add-note" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">New note</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form enctype="multipart/form-data" asp-action="AddCommentAsNote" data-returnUrl="@Url.Action("Notes", "Logbooks", new { area = "Management", Id = @Model.LogbookID })" method="post">
                <div class="modal-body" name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="form-group">
                        <input asp-for="UserID" value="@Model.UserID" type="hidden">
                    </div>
                    <select id="Logbook" name="Logbook" class="form-group">
                        <option value="">@ViewBag.logbooks</option>
                    </select>
                    <div class="form-group">
                        <label asp-for="@Model.Text">Note text</label>
                        <textarea class="form-control" asp-for="@Model.Text" rows="3" placeholder="Note text"></textarea>
                        <span asp-validation-for="@Model.Text" class="text-danger"></span>
                    </div>

                    <select id="Categories" asp-for="Categories" asp-items="ViewBag.categories"></select>
                    <div class="form-group">
                        <label asp-for="UploadFormPicture">Image</label>
                        <input type="file" name="UploadFormPicture" accept="image/*" class="form-control" />
                        <span asp-validation-for="UploadFormPicture" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" data-save="modal" class="btn btn-success">Add Note</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
    <script>
$('#Logbook').change(function () {
    var selectedValue = $(this).val();
    $.get({
        url: '@Url.Action("CategoryDropDownList", "Home")',
        data: { logbook: selectedValue },

        success: function (result) {

            alert(result);
            var categories = $('#Categories');
            categories.empty();

            $.each(result, function () {

                categories.append(
                        $('<option>', {
                            value: this.Value
                        }).text(this.Text)
                    );
            });
        }
    });
});
    </script>
}

FourthCircle/Areas/Management/Views/Logbooks/AddNote.cshtml
@using FourthCircle.Models.EntityViewModels;
@model NoteViewModel

<button type="button" class="add-note-button" data-toggle="modal" data-target="#exampleModal" data-whatever="getbootstrap"><img src="~/Icons/icons8-note-96.png"></button>

<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Add note</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <form enctype="multipart/form-data" asp-action="AddNoteAsync" data-returnUrl="@Url.Action("Notes", "Logbooks", new { area = "Management", Id = @Model.LogbookID })" method="post">
                <div class="modal-body" name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()">
                    <input name="IsValid" type="hidden" value="@ViewData.ModelState.IsValid.ToString()" />
                    <div class="form-group">
                        <input asp-for="LogbookID" value="@Model.LogbookID" type="hidden">
                    </div>
                    <div class="form-group">
                        <textarea class="form-control" asp-for="@Model.Text" rows="3" placeholder="Note text"></textarea>
                        <span asp-validation-for="@Model.Text" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <select asp-for="Categories" asp-items="ViewBag.categories" class="form-control"></select>
                    </div>
                    <div class="form-group custom-file">
                        <input type="file" name="UploadFormPicture" accept="image/JPEG" class="custom-file-input" id="customFile">
                        <label class="custom-file-label" for="customFile">Choose image</label>
                        <span asp-validation-for="UploadFormPicture" class="text-danger"></span>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <button type="submit" data-save="modal" class="btn btn-success">Add Note</button>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

FourthCircle/Areas/Management/Views/Logbooks/EditNote.cshtml
@model FourthCircle.Models.EntityViewModels.NoteViewModel

@{
    ViewData["Title"] = "AddNote";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit Note</h1>

<form asp-action="EditNote">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="form-group">
        <input asp-for="LogbookID" value="@Model.LogbookID" type="hidden">
        <input asp-for="UserID" value="@Model.UserID" type="hidden">
        <input asp-for="Id" value="@Model.Id" type="hidden">
    </div>
    <div class="form-group">
        <textarea class="form-control" asp-for="Text" rows="3" placeholder="Note text"></textarea>
        <span asp-validation-for="Text" class="text-danger"></span>
        <select asp-for="Categories" asp-items="ViewBag.categories"></select>
    </div>
    <div class="form-group">
        <button type="submit" class="btn btn-success">Save</button>
    </div>
</form>

<div>
    <a asp-action="Notes" asp-route-Id="@Model.LogbookID">Back to List</a>
</div>

FourthCircle/Areas/Management/Views/Logbooks/Index.cshtml
@model IEnumerable<LocationViewModel>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@foreach (var location in Model)
{
    <div class="btn-group-vertical">
        <button class="btn btn-primary">@location.Name</button> @*TODO: location comments*@
        @foreach (var logbook in location.Logbooks)
        {
            <a asp-area="Management" asp-controller="Logbooks" asp-action="Notes" asp-route-id="@logbook.Id" asp-route-showAll="false" class="btn btn-primary active">@logbook.Name</a>
        }
    </div>
    <br />
}

    <style>
        .btn-group-vertical {
            margin: 2px !important;
        }
        .btn-group-vertical {
      display: block;
      margin: 0 auto;
      text-align: center;
    }
    </style>

FourthCircle/Areas/Management/Views/Logbooks/Notes.cshtml
@using X.PagedList.Mvc.Core
@model X.PagedList.IPagedList<NoteViewModel>

@{
    ViewData["Title"] = "Notes";
    Layout = "~/Areas/Management/Views/Shared/_Layout.cshtml";
}

<br /><br />
<div id="add-note"></div>
<partial name="~/Areas/Management/Views/Logbooks/AddNote.cshtml" model="new NoteViewModel { LogbookID = ViewBag.logbookId }" />
<div id="notes">
    <ul class="list-unstyled">
        @foreach (var note in Model)
        {
            <li class="media text-dark bg-white mb-4 rounded-top">
                @if (note.UserAvatar != null)
                {
                    <img width="64" height="64" src="@Url.Action("GetUserAvatar", "Images", new { userId = note.UserID })" class="mr-3 rounded-circle" alt="@note.UserName's avatar"> @*float-left*@
                }
                else
                {
                    <img width="64" height="64" src="~/Icons/icons8-user-male-circle.png" class="mr-3 rounded-circle" alt="@note.UserName's avatar">
                }

                <div class="media-body">
                    @if (note.Categories != null)
                    {
                        @foreach (var category in note.Categories)
                        {
                            <a asp-action="Notes" asp-route-category="@category" asp-route-showAll="@ViewBag.showAll" class="badge badge-primary float-right m-2">@category</a>
                        }
                    }
                    <h5 class="mt-0 p-2 w-100">@note.UserName posted on @note.CreatedOn</h5>

                    @note.Text
                    <div class="float-right" id="note-navigation">
                        @if (note.IsMarkedAsSolved)
                        {
                            <img width="22" height="22" data-toggle="tooltip" data-placement="top" title="@note.SolvedByUser.UserName" src="@Url.Action("GetUserAvatar", "Images", new { userId = note.SolvedByUser.Id })" class="rounded-circle" alt="@note.SolvedByUser's avatar">
                            <img width="27" height="27" src="https://img.icons8.com/color/48/000000/checked-2.png">
                        }
                        <button type="button" class="btn btn-outline-info dropdown-toggle dropdown-toggle-split btn-sm" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <div class="dropdown-menu">
                            @if (note.UserName == User.Identity.Name)
                            {
                                <a asp-area="Management" asp-controller="Logbooks" asp-action="EditNote" asp-route-logbookId="@ViewBag.logbookId" asp-route-noteId="@note.Id" class="dropdown-item btn-outline-primary">Edit</a>
                                <a asp-area="Management" asp-controller="Logbooks" asp-action="DeleteNote" asp-route-logbookId="@ViewBag.logbookId" asp-route-noteId="@note.Id" class="dropdown-item btn-outline-warning" onclick="return confirm('Are you sure you want to delete this note?')">Delete</a>
                            }
                            @if (!note.IsMarkedAsSolved)
                            {
                                <a asp-area="Management" asp-controller="Logbooks" asp-action="MarkNoteAsSolved" asp-route-id="@note.Id" asp-route-logbookId="@ViewBag.logbookId" class="dropdown-item btn-outline-primary">Mark as solved</a>
                            }
                        </div>
                    </div>
                    @if (note.Picture != null)
                    {
                        <div class="mb-1 mt-1">
                            <img class="myImages" id="myImg" src="@Url.Action("GetUploadImage", "Images", new { noteId = note.Id })" alt="@note.Text" style="width:100%;max-width:72px">
                            <br />
                        </div>
                    }
                </div>
            </li>
        }
    </ul>


    <div id="myModal" class="modal">
        <span class="close-img-modal">&times;</span>
        <img class="modal-content" id="img01">
        <div id="caption"></div>
    </div>
</div>

@Html.PagedListPager((X.PagedList.IPagedList)Model, page => Url.Action("Notes", new { Id = ViewBag.logbookId, searchString = ViewBag.searchString, category = ViewBag.category, dateFrom = ViewBag.dateFrom, dateTo = ViewBag.dateTo, showAll = ViewBag.showAll, page }),
    new PagedListRenderOptionsBase
                {
                    LiElementClasses = new string[] { "page-item" },
                    PageClasses = new string[] { "page-link" }
                })


@section Scripts{
    <script type="text/javascript">
$(document).ready(function() {
    $("body").tooltip({ selector: '[data-toggle=tooltip]' });
});
    </script>

    <script type="text/javascript">
        $(function () {
            $("#datepicker").datepicker();
        });
    </script>
    <partial name="_ValidationScriptsPartial" />

    <script type="text/javascript">
        var modal = document.getElementById("myModal");

        var images = document.getElementsByClassName('myImages');
        var modalImg = document.getElementById("img01");
        var captionText = document.getElementById("caption");

        for (var i = 0; i < images.length; i++) {
            var img = images[i];
            img.onclick = function (evt) {
                modal.style.display = "block";
                modalImg.src = this.src;
                captionText.innerHTML = this.alt;
            }
        }

        var span = document.getElementsByClassName("close-img-modal")[0];

        span.onclick = function () {
            modal.style.display = "none";
        }
    </script>

    <script>
        $(".custom-file-input").on("change", function () {
            var fileName = $(this).val().split("\\").pop();
            $(this).siblings(".custom-file-label").addClass("selected").html(fileName);
        });
    </script>

    <script type="text/javascript">
    $(document).ready(function () {

        $("#dt1").datepicker({
            dateFormat: "dd-M-yy",
            minDate: 0,
            onSelect: function () {
                var dt2 = $('#dt2');
                var startDate = $(this).datepicker('getDate');
                var minDate = $(this).datepicker('getDate');
                var dt2Date = dt2.datepicker('getDate');
                var dateDiff = (dt2Date - minDate)/(86400 * 1000);

                startDate.setDate(startDate.getDate() + 30);
                if (dt2Date == null || dateDiff < 0) {
                		dt2.datepicker('setDate', minDate);
                }
                else if (dateDiff > 30){
                		dt2.datepicker('setDate', startDate);
                }
                dt2.datepicker('option', 'maxDate', startDate);
                dt2.datepicker('option', 'minDate', minDate);
            }
        });
        $('#dt2').datepicker({
            dateFormat: "dd-M-yy",
            minDate: 0
        });
    });
    </script>
}

<style>
    .add-note-button {
        position: fixed;
        bottom: 10em;
        left: 70%;
        border: none;
        border-color: none;
    }

    .add-note-button {
        -webkit-appearance: none;
        -moz-appearance: none;
        outline: none;
        border: 0;
        background: transparent;
    }

    #myImg {
        border-radius: 5px;
        cursor: pointer;
        transition: 0.3s;
    }

        #myImg:hover {
            opacity: 0.7;
        }

    .modal {
        display: none;
        position: fixed;
        padding-top: 100px;
        left: 0;
        top: 0;
        width: 100%;
        height: 100%;
        overflow: auto;
        background-color: rgb(0,0,0);
        background-color: rgba(0,0,0,0.9);
    }

    .modal-content {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
    }

    #caption {
        margin: auto;
        display: block;
        width: 80%;
        max-width: 700px;
        text-align: center;
        color: #ccc;
        padding: 10px 0;
        height: 150px;
    }

    .modal-content, #caption {
        animation-name: zoom;
        animation-duration: 0.6s;
    }

    @@keyframes zoom {
        from {
            transform: scale(0)
        }

        to {
            transform: scale(1)
        }
    }

    .close-img-modal {
        position: absolute;
        top: 15px;
        right: 35px;
        color: #f1f1f1;
        font-size: 40px;
        font-weight: bold;
        transition: 0.3s;
    }

        .close-img-modal:hover,
        .close-img-modal:focus {
            color: #bbb;
            text-decoration: none;
            cursor: pointer;
        }

    @@media only screen and (max-width: 700px) {
        .modal-content {
            width: 100%;
        }
    }
</style>